### PR TITLE
doc: introduce code coverage section

### PR DESCRIPTION
**Pull request by vlrpl**
as per title

### CODE REVIEW

**Comment by vlrpl** [comment]
I snuck into this the vagrant workaround removal as this should be fixed now. For that reason, the PR is labeled with `run-functional-tests`.

**Review by atenart — CHANGES_REQUESTED** [review]
A few comments:
- I tried using it and it seems `cargo-llvm-cov` needs to be installed as well as the rustup `llvm-tools-preview` component.
- Can you use an example for `toolchain` so users know what to look for?
- The `CARGO_OPTS` use should be in its own paragraph, but not in the default example.
- Since the html output is optional, maybe let's not use it in the default example but alongside the last paragraph. Eg. "for redability you can ...".

**Comment by vlrpl** [comment]
> A few comments:
> 
>     * I tried using it and it seems `cargo-llvm-cov` needs to be installed as well as the rustup `llvm-tools-preview` component.
> 

right, these are needed.

>     * Can you use an example for `toolchain` so users know what to look for?
> 

this could be whatever it is installed via rustup, so could be any version (maybe names can be assigned). 
I guess if we want this, we could use +nightly or +stable as those aliases should be safe enough.

>     * The `CARGO_OPTS` use should be in its own paragraph, but not in the default example.
> 
>     * Since the html output is optional, maybe let's not use it in the default example but alongside the last paragraph. Eg. "for redability you can ...".

ok, let's move optional stuff in their paragraph.

**Comment by atenart** [comment]
> > ```
> > * Can you use an example for `toolchain` so users know what to look for?
> > ```
> 
> this could be whatever it is installed via rustup, so could be any version (maybe names can be assigned). I guess if we want this, we could use +nightly or +stable as those aliases should be safe enough.

Could be any version, I think the explanation is good in this regards. I just think using whatever version for the example would gives an idea what is expected.

**Review by atenart — APPROVED** [review]
Looking good, thanks!

**Pull request merged**
