### PR TITLE
retrieve more info in the events (smp_id, csum & GSO)

### PR DESCRIPTION
**Pull request by atenart**

### CODE REVIEW

**Comment by atenart** [comment]
Rebased on top of main to fix the OvS runtime CI issue on Rawhide.

**Comment by atenart** [comment]
Fixed an issue with csum_start & csum_offset; and rebased on top of main to resolve a merge conflict.

**Review by vlrpl — COMMENTED** [review]
this fell through the cracks. I can't recall why we didn't include this before :)

**Review by vlrpl — APPROVED** [review]
this lgtm. Thanks!

**Comment by atenart** [comment]
Rebased on top of main to fix CI issues.

**Pull request merged**
